### ISSUE TITLE
Traceback, panel not working 

### ISSUE THREAD

**Issue by japrogramer** [Krukov/django-channels-panel#10]
django==1.11.4
django-channels-panel==0.0.5
django-debug-toolbar==1.8
django-redis==4.8.0

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/apps.py", line 17, in send
    'send', GROUP_NAME_CHANNELS)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 25, in send_debug
    Group(group).send({'text': json.dumps({'data': data, 'event': event, _MARK: _MARK}, cls=MessageJSONEncoder)})
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 20, in default
    return o.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 11: invalid continuation byte
2017-08-26 03:48:08,276 - ERROR - worker - Error processing message with consumer channels.staticfiles.StaticFilesConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/apps.py", line 17, in send
    'send', GROUP_NAME_CHANNELS)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 25, in send_debug
    Group(group).send({'text': json.dumps({'data': data, 'event': event, _MARK: _MARK}, cls=MessageJSONEncoder)})
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 20, in default
    return o.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 11: invalid start byte
2017-08-26 03:48:08,276 - ERROR - worker - Error processing message with consumer channels.staticfiles.StaticFilesConsumer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/apps.py", line 17, in send
    'send', GROUP_NAME_CHANNELS)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 25, in send_debug
    Group(group).send({'text': json.dumps({'data': data, 'event': event, _MARK: _MARK}, cls=MessageJSONEncoder)})
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/channels_panel/utils.py", line 20, in default
    return o.decode('utf-8')
```

**Comment by reyzavk** [comment]
I encountered the same problem, any fix yet?

**Comment by Krukov** [comment]
Sorry 
 Yes, fix in master branch. I have to release it.
